### ISSUE TITLE
Please add a license to this project.

### ISSUE THREAD

**Issue by pazaricha** [vimeo/player-api#69] opened 2015-03-24 08:30 UTC
Right now, legally speaking, this project is not open source.

What license the code in this repo is distributed under?

MIT? GPL? Apache?

**Comment by jodyheavener** [comment] 2015-04-15 17:51
+ Hey folks, need a license here!

**Comment by bdougherty** [comment] 2015-04-15 21:45
Duplicate of #62

**Closed by bdougherty** 2015-04-15 21:45 UTC
